version: '3.8'

services:
  app:
    build:
      args:
        user: dev
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: app
    container_name: app-project
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    networks:
      - project

  db:
    image: mysql:5.7
    container_name: app-db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - project

  nginx:
    image: nginx:alpine
    container_name: app-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      - ${APP_PATH_NGINX_HOST}:${APP_PATH_NGINX_CONTAINER}
    networks:
      - project

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: app-phpmyadmin
    ports:
      - 8080:80
    networks:
      - project

networks:
  project:
    driver: bridge
