version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      - ${APP_PATH_ERROR_REP_HOST}:${APP_PATH_ERROR_REP_CONTAINER}
    networks:
      - project

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - project

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      - ${APP_PATH_NGINX_HOST}:${APP_PATH_NGINX_CONTAINER}
    networks:
      - project

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    networks:
      - project

networks:
  project:
    driver: bridge
